#pragma once
#include <cmath>

#ifndef MOISE_SYNTH_H
#define MOISE_SYNTH_H

//Base class for MOISE synthesizers.
class MoiseSynth {
	//stepHz is a constant used to calculate the frequency of a note based on its MOISE_Note value
	static float stepHz;

protected:
	double currentTime; //The current time in seconds of the synth's active voice.
	float currentSample[2]; //Stores up to 2 channels of audio data for each sample taken from the synth.
	float frequency = 440; //The current frequency of playback, determined by the value of the NoteOn command.
	float pan = 0.5; //The sterep pan of the synth.
	double currentPosition = 0; //The current playback position of the synth's active voice.
	float currentEnvelopePosition; //The current position in the synth's envelope. NOTE: Envelopes are not yet implemented.
	float currentEnvelopeValue; //The current value of the envelope.
	int currentSamplePosition; //The current sample position of the synth's active voice when the synth uses a sample.
	int currentValue; //The current enum value of the note being played.
	int sampleRate; //The base sample rate of the sample.
	int channels; //The number of audio channels being used (1 = mono, 2 = stereo)
	bool active; //Whether or not the synth is currently active.
	bool initialized; //Whether or not the synth has been initialized.

public:
	MoiseSynth() {

	}

	/// <summary>
	/// Initializes the synth with the provided sample rate and number of channels.
	/// </summary>
	/// <param name="setSampleRate">The sample rate of the synth</param>
	/// <param name="setChannels">The number of channels of the synth</param>
	void Initialize(int setSampleRate, int setChannels) {
		sampleRate = setSampleRate;
		channels = setChannels;
		stepHz = std::pow(2.0, 1.0 / 12.0); 
		initialized = true;
	}

	/// <summary>
	/// Used for testing purposes. In the sample player synth, this returns the value of the waveform at the provided sample index.
	/// If a synth is using the base clas function, it will return -1.
	/// </summary>
	/// <param name="sampleIndex">The sample index to check</param>
	/// <returns></returns>
	virtual float GetWaveformValue(int sampleIndex) {
		return -1;
	}

	/// <summary>
	/// Returns the value of the next sample to be generated by the synth, advancing the synth's internal time by the provided timeAdvance value. This base class function produces a sine wave tone.
	/// </summary>
	/// <param name="timeAdvance">The amount of time to advance the synth playback</param>
	/// <returns></returns>
	virtual float* GetNextSample(double timeAdvance) {
		for (int i = 0; i < channels; i++) {
			currentSample[i] = std::sin(2 * 3.14159265358979323846 * frequency * currentTime);
		}

		currentTime += timeAdvance;
		
		return currentSample;
	}

	/// <summary>
	/// Activates the synth voice and sets the note it's playing to the given value.
	/// </summary>
	/// <param name="value"></param>
	virtual void NoteOn(int value) {
		active = true;
		frequency = 440 * std::pow(stepHz, value);
		currentValue = value;
		currentPosition = 0;
	}
};

#endif // !MOISE_SYNTH_H
